name = "buape-com"
main = ".open-next/worker.js"
compatibility_date = "2025-01-28"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[observability.logs]
enabled = true
